### ISSUE TITLE
the background is not actually from doom

### ISSUE THREAD

**Issue by makc** [vivirenremoto/doomcaptcha#9]
this is from win95 screensaver:
![gif](https://thumbs.gfycat.com/TimelyAbandonedIberianemeraldlizard.webp)

here are few doom reference images for you:
![1](https://www.shadertoy.com/media/shaders/lsSXzD.jpg)
![2](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/68dccc19-ea17-4abf-b66e-ed282c1fc746/deh3wl5-239a0de1-5984-4960-8481-b3d7667c79ef.png)
![3](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/68dccc19-ea17-4abf-b66e-ed282c1fc746/deh3xfp-d5d557be-6b28-43c5-aa70-dd5a56012ec2.png/v1/fill/w_1192,h_670,q_70,strp/__doom_____e1m6_central_processing_dl_by_guiltronprime_deh3xfp-pre.jpg)

**Comment by vivirenremoto** [comment]
hello !

first of all thank you for taking your precious time to send this background :)

i know that the backgorund is not from doom, i did it because this way the enemy stands out from the background and it fits with the retro style.

i tried the images you sent and maybe it will be clear what i'm trying to talk about.

![Screenshot (71)](https://user-images.githubusercontent.com/448403/120065099-eae96800-c06f-11eb-9795-e29ec89acf13.png)

![Screenshot (70)](https://user-images.githubusercontent.com/448403/120065101-ed4bc200-c06f-11eb-819f-f72e3c91c41f.png)

![Screenshot (69)](https://user-images.githubusercontent.com/448403/120065102-ee7cef00-c06f-11eb-8438-ba2f7b597a1b.png)

![Screenshot (72)](https://user-images.githubusercontent.com/448403/120065243-9692b800-c070-11eb-9cbb-aa16ef06cee9.png)

**Comment by makc** [comment]
if you wanted the contrast, you could have used one of the red boys instead of imps:

![](https://media.tenor.com/images/83ed342e20601308985c205a76c1f5f2/tenor.gif)
![](https://i.makeagif.com/media/7-31-2015/wMabfn.gif)
![](https://retrobeargaming.files.wordpress.com/2013/01/new_classic_doom_enem_baron1.gif)

**Comment by vivirenremoto** [comment]
maybe it will be good idea to show a random background

**Comment by vivirenremoto** [comment]
i made this commit to show random backgrounds, thank you for your contributions @makc 
https://github.com/vivirenremoto/doomcaptcha/commit/3d3e6d6596eb7a38906596c9dd5b14c9a07c3fd1

the idea to change the enemies is a good one too, give me some time to think about it

**Comment by vivirenremoto** [comment]
i just added some different enemies, thank you again @makc 
https://github.com/vivirenremoto/doomcaptcha/commit/29d703370a3ea4323d5419a9b6bd617875684fa2
